apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: monitoring
spec:
  type: ExternalName
  externalName: 172.18.0.3
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
