apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: homecredit
spec:
  feastProject: homecredit
  feastProjectDir: 
    git:
      url: {{ .Values.feastProjectDir.git.url }}
      ref: {{ .Values.feastProjectDir.git.ref }}
      featureRepoPath: {{ .Values.feastProjectDir.git.featureRepoPath }}
  services:      
    registry:
      local:
        server:
          image: {{ .Values.image | quote}}
          imagePullPolicy: IfNotPresent
          logLevel: debug
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
    offlineStore:
      server:
        image: {{ .Values.image | quote }}  
        imagePullPolicy: IfNotPresent
        logLevel: debug
      persistence:
        store:
          type: spark
          secretRef:
            name: feast-data-stores
    onlineStore:
      server:
        image: {{ .Values.image | quote }}
        imagePullPolicy: IfNotPresent
        logLevel: debug
      persistence:
        store:
          type: redis
          secretRef:
            name: feast-data-stores
    ui:
      image: {{ .Values.image | quote }}
      imagePullPolicy: IfNotPresent
      logLevel: debug
  cronJob:
    containerConfigs:
      image: {{ .Values.image | quote }}
      imagePullPolicy: IfNotPresent
    schedule: "@hourly"
    timeZone: "Asia/Ho_Chi_Minh"
    concurrencyPolicy: "Forbid"
