apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
stringData:
  postgres: |
    host: ${POSTGRES_HOST}
    port: 5432
    database: ${POSTGRES_DB}
    db_schema: homecredit
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  bigquery: |
    dataset: homecredit_ds
# ---
# apiVersion: v1 
# kind: Secret
# metadata:
#   name: gcloud-creds
# stringData:
#   application_default_credentials.json: |
# {{ .Values.gcloudCredentials | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
stringData:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}


