replicaCount: 1

image:
  repository: microwave1005/prediction-api
  tag: latest 
  pullPolicy: IfNotPresent

service:
  name: prediction-api
  namespace: api
  ports:
    http: 8000
    metrics: 8001

env:
  S3_ENDPOINT: "minio.minio.svc.cluster.local:9000"
  MLFLOW_ENDPOINT: "http://mlflow.mlflow.svc.cluster.local:5000"
  PARENT_RUN_ID: "b70cff138a974ea6a6a7db9de67f25e6"
  TRANSFORMER_ARTIFACT_PATH: "prep/transformer_joblib"

secrets:
  accessKeyName: minio-creds
  accessKeyId: "minio"
  secretAccessKey: "minio123"  

monitoring:
  enabled: true
  releaseLabel: kps
  interval: 15s

ingress:
  enabled: false
  ingressClassName: nginx
  annotations: {}
  rules: []
