channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=25.0.1
- pip:
  - mlflow==2.8.1
  - lz4==4.3.3
  - numpy==1.24.4
  - pandas==2.1.3
  - psutil==5.9.8
  - scikit-learn==1.6.1
  - scipy==1.15.1
  - xgboost==2.1.4
name: mlflow-env
