{
  "type": "record",
  "namespace": "com.example",
  "name": "CreditCardBalance",
  "fields": [
    {
      "name": "SK_ID_PREV",
      "type": "long"
    },
    {
      "name": "SK_ID_CURR",
      "type": "long"
    },
    {
      "name": "MONTHS_BALANCE",
      "type": "int"
    },
    {
      "name": "AMT_BALANCE",
      "type": "double"
    },
    {
      "name": "AMT_CREDIT_LIMIT_ACTUAL",
      "type": "long"
    },
    {
      "name": "AMT_DRAWINGS_ATM_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_DRAWINGS_CURRENT",
      "type": "double"
    },
    {
      "name": "AMT_DRAWINGS_OTHER_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_DRAWINGS_POS_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_INST_MIN_REGULARITY",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_PAYMENT_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_PAYMENT_TOTAL_CURRENT",
      "type": "double"
    },
    {
      "name": "AMT_RECEIVABLE_PRINCIPAL",
      "type": "double"
    },
    {
      "name": "AMT_RECIVABLE",
      "type": "double"
    },
    {
      "name": "AMT_TOTAL_RECEIVABLE",
      "type": "double"
    },
    {
      "name": "CNT_DRAWINGS_ATM_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "CNT_DRAWINGS_CURRENT",
      "type": "int"
    },
    {
      "name": "CNT_DRAWINGS_OTHER_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "CNT_DRAWINGS_POS_CURRENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "CNT_INSTALMENT_MATURE_CUM",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "NAME_CONTRACT_STATUS",
      "type": "string"
    },
    {
      "name": "SK_DPD",
      "type": "int"
    },
    {
      "name": "SK_DPD_DEF",
      "type": "int"
    }
  ]
}