{
  "type": "record",
  "namespace": "com.example",
  "name": "InstallmentsPayments",
  "fields": [
    {
      "name": "SK_ID_PREV",
      "type": "long"
    },
    {
      "name": "SK_ID_CURR",
      "type": "long"
    },
    {
      "name": "NUM_INSTALMENT_VERSION",
      "type": "double"
    },
    {
      "name": "NUM_INSTALMENT_NUMBER",
      "type": "int"
    },
    {
      "name": "DAYS_INSTALMENT",
      "type": "double"
    },
    {
      "name": "DAYS_ENTRY_PAYMENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_INSTALMENT",
      "type": "double"
    },
    {
      "name": "AMT_PAYMENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    }
  ]
}