{
  "type": "record",
  "namespace": "com.example",
  "name": "POSCashBalance",
  "fields": [
    {
      "name": "SK_ID_PREV",
      "type": "long"
    },
    {
      "name": "SK_ID_CURR",
      "type": "long"
    },
    {
      "name": "MONTHS_BALANCE",
      "type": "int"
    },
    {
      "name": "CNT_INSTALMENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "CNT_INSTALMENT_FUTURE",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "NAME_CONTRACT_STATUS",
      "type": "string"
    },
    {
      "name": "SK_DPD",
      "type": "int"
    },
    {
      "name": "SK_DPD_DEF",
      "type": "int"
    }
  ]
}