{
  "type": "record",
  "namespace": "com.example",
  "name": "PreviousApplication",
  "fields": [
    {
      "name": "SK_ID_PREV",
      "type": "long"
    },
    {
      "name": "SK_ID_CURR",
      "type": "long"
    },
    {
      "name": "NAME_CONTRACT_TYPE",
      "type": "string"
    },
    {
      "name": "AMT_ANNUITY",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_APPLICATION",
      "type": "double"
    },
    {
      "name": "AMT_CREDIT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_DOWN_PAYMENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "AMT_GOODS_PRICE",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "WEEKDAY_APPR_PROCESS_START",
      "type": "string"
    },
    {
      "name": "HOUR_APPR_PROCESS_START",
      "type": "int"
    },
    {
      "name": "FLAG_LAST_APPL_PER_CONTRACT",
      "type": "string"
    },
    {
      "name": "NFLAG_LAST_APPL_IN_DAY",
      "type": "int"
    },
    {
      "name": "RATE_DOWN_PAYMENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "RATE_INTEREST_PRIMARY",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "RATE_INTEREST_PRIVILEGED",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "NAME_CASH_LOAN_PURPOSE",
      "type": "string"
    },
    {
      "name": "NAME_CONTRACT_STATUS",
      "type": "string"
    },
    {
      "name": "DAYS_DECISION",
      "type": "int"
    },
    {
      "name": "NAME_PAYMENT_TYPE",
      "type": "string"
    },
    {
      "name": "CODE_REJECT_REASON",
      "type": "string"
    },
    {
      "name": "NAME_TYPE_SUITE",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "NAME_CLIENT_TYPE",
      "type": "string"
    },
    {
      "name": "NAME_GOODS_CATEGORY",
      "type": "string"
    },
    {
      "name": "NAME_PORTFOLIO",
      "type": "string"
    },
    {
      "name": "NAME_PRODUCT_TYPE",
      "type": "string"
    },
    {
      "name": "CHANNEL_TYPE",
      "type": "string"
    },
    {
      "name": "SELLERPLACE_AREA",
      "type": "int"
    },
    {
      "name": "NAME_SELLER_INDUSTRY",
      "type": "string"
    },
    {
      "name": "CNT_PAYMENT",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "NAME_YIELD_GROUP",
      "type": "string"
    },
    {
      "name": "PRODUCT_COMBINATION",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "DAYS_FIRST_DRAWING",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "DAYS_FIRST_DUE",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "DAYS_LAST_DUE_1ST_VERSION",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "DAYS_LAST_DUE",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "DAYS_TERMINATION",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "NFLAG_INSURED_ON_APPROVAL",
      "type": [
        "null",
        "double"
      ],
      "default": null
    }
  ]
}