apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
        - name: api
          image: microwave1005/prediction-api-gcp:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 8000  # FastAPI
            - containerPort: 8001  # Prometheus metrics
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  namespace: monitoring
  labels:
    app: prediction-api
spec:
  selector:
    app: prediction-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 8001
      targetPort: 8001
      name: metrics
