global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
- name: discord
  webhook_configs:
  - url: "https://discord.com/api/webhooks/1362697322852778105/zKSadmnhZrhx-k8J8j8rND1PBpfedn-87joOgUuiDMHnKnXfuOVIypnI_lMYP29ASIm2"
    send_resolved: true
