# k8s/drift-monitor-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-monitor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-monitor
  template:
    metadata:
      labels:
        app: drift-monitor
    spec:
      containers:
        - name: monitor
          image: microwave1005/drift-monitor:latest
          command: ["python", "/app/monitor.py"]
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service.kubeflow.svc.cluster.local:9000"
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
            - name: MINIO_BUCKET_NAME
              value: "sample-data"
          ports:
            - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: drift-monitor
  namespace: monitoring
spec:
  selector:
    app: drift-monitor
  ports:
    - port: 8001
      targetPort: 8001
