apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  namespace: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: app
          image: microwave1005/streamlit-app:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
  namespace: streamlit
spec:
  selector:
    app: streamlit-app
  ports:
    - name: http
      port: 8501
      targetPort: 8501
