apiVersion: batch/v1
kind: Job
metadata:
  name: insert-bureau-balance
  namespace: database
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 5000
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: insertion
        image: microwave1005/insert-job:0.0.2
        imagePullPolicy: IfNotPresent
        command: ["python3", "insert_data.py"]
        args:
          ["--schema","record",
           "--user","postgres",
           "--password","postgres",          
           "--dbname","homecredit",
           "--host","postgres.database.svc.cluster.local",
           "--port","5432",
           "--minio-endpoint","minio.minio.svc.cluster.local:9000",
           "--minio-access-key","minio",
           "--minio-secret-key","minio123",
           "--table","bureau_balance",
           "--bucket","sample-data",
           "--file","bureau_balance.csv"]
