CREATE TABLE application
(
    SK_ID_CURR Int64,
    NAME_CONTRACT_TYPE String,
    CODE_GENDER String,
    FLAG_OWN_CAR String,
    FLAG_OWN_REALTY String,
    CNT_CHILDREN Int32,
    AMT_INCOME_TOTAL Float64,
    AMT_CREDIT Float64,
    AMT_ANNUITY Float64,
    AMT_GOODS_PRICE Float64,
    NAME_TYPE_SUITE String,
    NAME_INCOME_TYPE String,
    NAME_EDUCATION_TYPE String,
    NAME_FAMILY_STATUS String,
    NAME_HOUSING_TYPE String,
    REGION_POPULATION_RELATIVE Float64,
    DAYS_BIRTH Int32,
    DAYS_EMPLOYED Int32,
    DAYS_REGISTRATION Float64,
    DAYS_ID_PUBLISH Int32,
    OWN_CAR_AGE Float64,
    FLAG_MOBIL Int32,
    FLAG_EMP_PHONE Int32,
    FLAG_WORK_PHONE Int32,
    FLAG_CONT_MOBILE Int32,
    FLAG_PHONE Int32,
    FLAG_EMAIL Int32,
    OCCUPATION_TYPE String,
    CNT_FAM_MEMBERS Float64,
    REGION_RATING_CLIENT Int32,
    REGION_RATING_CLIENT_W_CITY Int32,
    WEEKDAY_APPR_PROCESS_START String,
    HOUR_APPR_PROCESS_START Int32,
    REG_REGION_NOT_LIVE_REGION Int32,
    REG_REGION_NOT_WORK_REGION Int32,
    LIVE_REGION_NOT_WORK_REGION Int32,
    REG_CITY_NOT_LIVE_CITY Int32,
    REG_CITY_NOT_WORK_CITY Int32,
    LIVE_CITY_NOT_WORK_CITY Int32,
    ORGANIZATION_TYPE String,
    EXT_SOURCE_1 Float64,
    EXT_SOURCE_2 Float64,
    EXT_SOURCE_3 Float64,
    APARTMENTS_AVG Float64,
    BASEMENTAREA_AVG Float64,
    YEARS_BEGINEXPLUATATION_AVG Float64,
    YEARS_BUILD_AVG Float64,
    COMMONAREA_AVG Float64,
    ELEVATORS_AVG Float64,
    ENTRANCES_AVG Float64,
    FLOORSMAX_AVG Float64,
    FLOORSMIN_AVG Float64,
    LANDAREA_AVG Float64,
    LIVINGAPARTMENTS_AVG Float64,
    LIVINGAREA_AVG Float64,
    NONLIVINGAPARTMENTS_AVG Float64,
    NONLIVINGAREA_AVG Float64,
    APARTMENTS_MODE Float64,
    BASEMENTAREA_MODE Float64,
    YEARS_BEGINEXPLUATATION_MODE Float64,
    YEARS_BUILD_MODE Float64,
    COMMONAREA_MODE Float64,
    ELEVATORS_MODE Float64,
    ENTRANCES_MODE Float64,
    FLOORSMAX_MODE Float64,
    FLOORSMIN_MODE Float64,
    LANDAREA_MODE Float64,
    LIVINGAPARTMENTS_MODE Float64,
    LIVINGAREA_MODE Float64,
    NONLIVINGAPARTMENTS_MODE Float64,
    NONLIVINGAREA_MODE Float64,
    APARTMENTS_MEDI Float64,
    BASEMENTAREA_MEDI Float64,
    YEARS_BEGINEXPLUATATION_MEDI Float64,
    YEARS_BUILD_MEDI Float64,
    COMMONAREA_MEDI Float64,
    ELEVATORS_MEDI Float64,
    ENTRANCES_MEDI Float64,
    FLOORSMAX_MEDI Float64,
    FLOORSMIN_MEDI Float64,
    LANDAREA_MEDI Float64,
    LIVINGAPARTMENTS_MEDI Float64,
    LIVINGAREA_MEDI Float64,
    NONLIVINGAPARTMENTS_MEDI Float64,
    NONLIVINGAREA_MEDI Float64,
    FONDKAPREMONT_MODE String,
    HOUSETYPE_MODE String,
    TOTALAREA_MODE Float64,
    WALLSMATERIAL_MODE String,
    EMERGENCYSTATE_MODE String,
    OBS_30_CNT_SOCIAL_CIRCLE Float64,
    DEF_30_CNT_SOCIAL_CIRCLE Float64,
    OBS_60_CNT_SOCIAL_CIRCLE Float64,
    DEF_60_CNT_SOCIAL_CIRCLE Float64,
    DAYS_LAST_PHONE_CHANGE Float64,
    FLAG_DOCUMENT_2 Int32,
    FLAG_DOCUMENT_3 Int32,
    FLAG_DOCUMENT_4 Int32,
    FLAG_DOCUMENT_5 Int32,
    FLAG_DOCUMENT_6 Int32,
    FLAG_DOCUMENT_7 Int32,
    FLAG_DOCUMENT_8 Int32,
    FLAG_DOCUMENT_9 Int32,
    FLAG_DOCUMENT_10 Int32,
    FLAG_DOCUMENT_11 Int32,
    FLAG_DOCUMENT_12 Int32,
    FLAG_DOCUMENT_13 Int32,
    FLAG_DOCUMENT_14 Int32,
    FLAG_DOCUMENT_15 Int32,
    FLAG_DOCUMENT_16 Int32,
    FLAG_DOCUMENT_17 Int32,
    FLAG_DOCUMENT_18 Int32,
    FLAG_DOCUMENT_19 Int32,
    FLAG_DOCUMENT_20 Int32,
    FLAG_DOCUMENT_21 Int32,
    AMT_REQ_CREDIT_BUREAU_HOUR Float64,
    AMT_REQ_CREDIT_BUREAU_DAY Float64,
    AMT_REQ_CREDIT_BUREAU_WEEK Float64,
    AMT_REQ_CREDIT_BUREAU_MON Float64,
    AMT_REQ_CREDIT_BUREAU_QRT Float64,
    AMT_REQ_CREDIT_BUREAU_YEAR Float64
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_CURR);

----------------
CREATE TABLE bureau
(
    SK_ID_CURR Int64,
    SK_ID_BUREAU Int64,
    CREDIT_ACTIVE String,
    CREDIT_CURRENCY String,
    DAYS_CREDIT Int32,
    CREDIT_DAY_OVERDUE Int32,
    DAYS_CREDIT_ENDDATE Float64,
    DAYS_ENDDATE_FACT Float64,
    AMT_CREDIT_MAX_OVERDUE Float64,
    CNT_CREDIT_PROLONG Int32,
    AMT_CREDIT_SUM Float64,
    AMT_CREDIT_SUM_DEBT Float64,
    AMT_CREDIT_SUM_LIMIT Float64,
    AMT_CREDIT_SUM_OVERDUE Float64,
    CREDIT_TYPE String,
    DAYS_CREDIT_UPDATE Int32,
    AMT_ANNUITY Float64
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_BUREAU)
ORDER BY (SK_ID_BUREAU);

----------------
CREATE TABLE bureau_balance
(
    SK_ID_BUREAU   Int64,
    MONTHS_BALANCE Int32,
    STATUS         String
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_BUREAU, MONTHS_BALANCE)
ORDER BY  (SK_ID_BUREAU, MONTHS_BALANCE);

----------------
CREATE TABLE previous_application
(
    SK_ID_PREV                   Int64,
    SK_ID_CURR                   Int64,
    NAME_CONTRACT_TYPE           String,
    AMT_ANNUITY                  Float64,
    AMT_APPLICATION              Float64,
    AMT_CREDIT                   Float64,
    AMT_DOWN_PAYMENT             Float64,
    AMT_GOODS_PRICE              Float64,
    WEEKDAY_APPR_PROCESS_START   String,
    HOUR_APPR_PROCESS_START      Int32,
    FLAG_LAST_APPL_PER_CONTRACT  String,
    NFLAG_LAST_APPL_IN_DAY       Int32,
    RATE_DOWN_PAYMENT            Float64,
    RATE_INTEREST_PRIMARY        Float64,
    RATE_INTEREST_PRIVILEGED     Float64,
    NAME_CASH_LOAN_PURPOSE       String,
    NAME_CONTRACT_STATUS         String,
    DAYS_DECISION                Int32,
    NAME_PAYMENT_TYPE            String,
    CODE_REJECT_REASON           String,
    NAME_TYPE_SUITE              String,
    NAME_CLIENT_TYPE             String,
    NAME_GOODS_CATEGORY          String,
    NAME_PORTFOLIO               String,
    NAME_PRODUCT_TYPE            String,
    CHANNEL_TYPE                 String,
    SELLERPLACE_AREA             Int32,
    NAME_SELLER_INDUSTRY         String,
    CNT_PAYMENT                  Float64,
    NAME_YIELD_GROUP             String,
    PRODUCT_COMBINATION          String,
    DAYS_FIRST_DRAWING           Float64,
    DAYS_FIRST_DUE               Float64,
    DAYS_LAST_DUE_1ST_VERSION    Float64,
    DAYS_LAST_DUE                Float64,
    DAYS_TERMINATION             Float64,
    NFLAG_INSURED_ON_APPROVAL    Float64
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_PREV)
ORDER BY  (SK_ID_PREV);
----------------
CREATE TABLE pos_cash_balance
(
    SK_ID_PREV            Int64,
    SK_ID_CURR            Int64,
    MONTHS_BALANCE        Int32,
    CNT_INSTALMENT        Float64,
    CNT_INSTALMENT_FUTURE Float64,
    NAME_CONTRACT_STATUS  String,
    SK_DPD                Int32,
    SK_DPD_DEF            Int32
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE)
ORDER BY  (SK_ID_PREV, MONTHS_BALANCE);

----------------
CREATE TABLE credit_card_balance
(
    SK_ID_PREV                      Int64,
    SK_ID_CURR                      Int64,
    MONTHS_BALANCE                  Int32,
    AMT_BALANCE                     Float64,
    AMT_CREDIT_LIMIT_ACTUAL         Int64,
    AMT_DRAWINGS_ATM_CURRENT        Float64,
    AMT_DRAWINGS_CURRENT            Float64,
    AMT_DRAWINGS_OTHER_CURRENT      Float64,
    AMT_DRAWINGS_POS_CURRENT        Float64,
    AMT_INST_MIN_REGULARITY         Float64,
    AMT_PAYMENT_CURRENT             Float64,
    AMT_PAYMENT_TOTAL_CURRENT       Float64,
    AMT_RECEIVABLE_PRINCIPAL        Float64,
    AMT_RECIVABLE                   Float64,   
    AMT_TOTAL_RECEIVABLE            Float64,
    CNT_DRAWINGS_ATM_CURRENT        Float64,
    CNT_DRAWINGS_CURRENT            Int32,
    CNT_DRAWINGS_OTHER_CURRENT      Float64,
    CNT_DRAWINGS_POS_CURRENT        Float64,
    CNT_INSTALMENT_MATURE_CUM       Float64,
    NAME_CONTRACT_STATUS            String,
    SK_DPD                          Int32,
    SK_DPD_DEF                      Int32
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE)
ORDER BY  (SK_ID_PREV, MONTHS_BALANCE);

---------------------------------------
CREATE TABLE installments_payments
(
    SK_ID_PREV              Int64,
    SK_ID_CURR              Int64,
    NUM_INSTALMENT_VERSION  Float64,
    NUM_INSTALMENT_NUMBER   Int32,
    DAYS_INSTALMENT         Float64,
    DAYS_ENTRY_PAYMENT      Float64,
    AMT_INSTALMENT          Float64,
    AMT_PAYMENT             Float64
)
ENGINE = MergeTree
PRIMARY KEY (SK_ID_PREV, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER)
ORDER BY  (SK_ID_PREV, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER);
