apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scipy-notebook-pvc
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: scipy-notebook
  namespace: kubeflow-user-example-com
  labels:
    access-ml-pipeline: "true"  
spec:
  template:
    spec:
      containers:
        - name: notebook
          image: microwave1005/scipy-img
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          volumeMounts:
            - mountPath: /home/jovyan/work
              name: scipy-notebook-workspace
      volumes:
        - name: scipy-notebook-workspace
          persistentVolumeClaim:
            claimName: scipy-notebook-pvc
