route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1359382517920174152/JcoJBK_JDRgqHyLdaAcT5RBRSJ0YsLTPz5jf7rEn5FgVzJfMkXLjTQuUMpl4VyamKvUO