import os

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")


SCHEMA_REGISTRY_CONFIG = {
    "url": os.getenv("SCHEMA_REGISTRY_URL")
}

APPLICATION_TOPIC = os.getenv("APPLICATION_TOPIC")
MERGED_TOPIC = os.getenv("MERGED_TOPIC")

SILVER_PATH_APPLICATION = os.getenv("SILVER_PATH_APPLICATION")
CHECKPOINT_PATH_APPLICATION = os.getenv("CHECKPOINT_PATH_APPLICATION")

SILVER_PATH_MERGED = os.getenv("SILVER_PATH_MERGED")
CHECKPOINT_PATH_MERGED = os.getenv("CHECKPOINT_PATH_MERGED")

GOLD_PATH = os.getenv("GOLD_PATH")