FROM apache/superset:5.0.0-py311

USER root
RUN apt-get update && apt-get install -y gcc libpq-dev wget tar \
 && rm -rf /var/lib/apt/lists/*

ENV PLAYWRIGHT_BROWSERS_PATH=/usr/local/share/playwright-browsers

RUN apt-get update && apt-get install -y wget \
  && wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
  && rm dockerize-linux-amd64-v0.6.1.tar.gz \
  && apt-get clean
  
COPY requirements_superset.txt /app/
RUN . /app/.venv/bin/activate && uv pip install --no-cache-dir -r /app/requirements_superset.txt \
  && playwright install-deps \
  && PLAYWRIGHT_BROWSERS_PATH=/usr/local/share/playwright-browsers playwright install chromium

USER superset