FROM google/cloud-sdk:slim

# Install kubectl 
RUN curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

RUN apt-get update && apt-get install -y git && apt-get clean

# Dummy entrypoint for Jenkins agent to attach
ENTRYPOINT [ "cat" ]
