FROM apache/spark:4.0.0-scala2.13-java17-ubuntu

USER root

RUN apt-get update && apt-get install -y \
    python3 python3-pip curl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/python3 /usr/bin/python \
 && python3 --version && pip --version

COPY requirements_spark.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src/batch_processing/spark_etl /opt/app

# Thêm JARs cần thiết vào classpath của Spark
WORKDIR /opt/spark/jars

# 1) Hadoop AWS (S3A)
RUN curl -fSL -o hadoop-aws-3.3.4.jar \
  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar

# 2) AWS SDK v1 bundle (PHÙ HỢP với hadoop-aws 3.3.4)
RUN curl -fSL -o aws-java-sdk-bundle-1.12.772.jar \
  https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.772/aws-java-sdk-bundle-1.12.772.jar

# 3) Delta Lake for Spark 4 (đã gồm delta-storage)
RUN curl -fSL -o delta-spark_2.13-4.0.0.jar \
  https://repo1.maven.org/maven2/io/delta/delta-spark_2.13/4.0.0/delta-spark_2.13-4.0.0.jar

# 4) Avro
RUN curl -fSL -o spark-avro_2.13-4.0.0.jar \
  https://repo1.maven.org/maven2/org/apache/spark/spark-avro_2.13/4.0.0/spark-avro_2.13-4.0.0.jar

# 5) Kafka Source/Sink cho Structured Streaming
RUN curl -fSL -o spark-sql-kafka-0-10_2.13-4.0.0.jar \
  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.13/4.0.0/spark-sql-kafka-0-10_2.13-4.0.0.jar
RUN curl -fSL -o spark-token-provider-kafka-0-10_2.13-4.0.0.jar \
  https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.13/4.0.0/spark-token-provider-kafka-0-10_2.13-4.0.0.jar


RUN curl -fSL -o /opt/flink/lib/kafka-clients-4.0.0.jar \
  https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/4.0.0/kafka-clients-4.0.0.jar

USER spark

