FROM python:3.11.11-slim

WORKDIR /app

COPY ../src/kfp_outside/requirements.txt ./requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install pytest==8.3.4

ENTRYPOINT []
CMD ["/bin/bash"]
    