apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: silver-application
  namespace: kubeflow
spec:
  type: Python
  mode: cluster
  image: microwave1005/spark-application:0.0.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/app/silver_layer/application_silver_layer.py
  sparkVersion: "4.0.0"
  restartPolicy:
    type: Never
  driver:
    serviceAccount: spark
    cores: 1
    memory: 1g
  executor:
    instances: 1
    cores: 1
    memory: 1g
    labels:
      version: 4.0.0
  env:
      - name: MINIO_ENDPOINT
        value: "http://minio.minio.svc.cluster.local:9000"
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-cred
            key: accessKey
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-cred
            key: secretKey
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "kafka-cluster-0-kafka-bootstrap:9092:9092"
      - name: APPLICATION_TOPIC
        value: "application-topic"
      - name: MERGED_TOPIC
        value: "merged-topic"
      - name: SCHEMA_REGISTRY_URL
        value: "http://schema-registry:8081"
      - name: SILVER_PATH_APPLICATION
        value: "s3a://silver/application"
      - name: CHECKPOINT_PATH_APPLICATION
        value: "s3a://checkpoints/application"
      - name: SILVER_PATH_MERGED
        value: "s3a://silver/merged"
      - name: CHECKPOINT_PATH_MERGED
        value: "s3a://checkpoints/merged"
      - name: GOLD_PATH
        value: "s3a://gold"
  sparkConf:
    spark.default.parallelism: "2"
    spark.sql.shuffle.partitions: "2"
    spark.sql.session.timeZone: "UTC"
    spark.ui.enabled: "true"
