apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-lb
  namespace: istio-system
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    - name: http
      port: 80
      targetPort: 8080   
    - name: https
      port: 443
      targetPort: 8443   
