backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgres.database.svc.cluster.local
    port: 5432
    database: homecredit
    user: postgres
    password: postgres

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123

extraEnvVars:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_REGION: us-east-1
  MLFLOW_S3_ENDPOINT_URL: http://minio.database.svc.cluster.local:9000
  MLFLOW_S3_IGNORE_TLS: "true"
  AWS_S3_ADDRESSING_STYLE: "path"

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mlflow.ducdh.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
