ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mlflow.ducdh.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

artifactRoot:
  gcs:
    enabled: true
    bucket: ducdh-bucket
    path: mlflow  # Optional: GCS bucket folder

extraEnvVars:
  GOOGLE_APPLICATION_CREDENTIALS: /etc/gcs/key.json
  MLFLOW_GCS_DEFAULT_TIMEOUT: "120"  # 2 minutes
  MLFLOW_GCS_UPLOAD_CHUNK_SIZE: "209715200"  # 200MB
  MLFLOW_GCS_DOWNLOAD_CHUNK_SIZE: "209715200"  # 200MB

extraVolumes:
  - name: gcs-credentials
    secret:
      secretName: gcs-credentials

extraVolumeMounts:
  - name: gcs-credentials
    mountPath: /etc/gcs
    readOnly: true