apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-jenkins
  template:
    metadata:
      labels:
        app: custom-jenkins
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}  # Dùng volume tạm
