apiVersion: v1
kind: Service
metadata:
  name: custom-jenkins
spec:
  selector:
    app: custom-jenkins
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
    - port: {{ .Values.service.agentPort }}
      targetPort: 50000
      name: agent
  type: {{ .Values.service.type }}
