substitutions:
  _MODEL_NAME: ""

steps:
- name: "docker.io/microwave1005/scipy-img"
  entrypoint: bash
  args:
    - -c
    - |
      export MLFLOW_TRACKING_URI="http://mlflow.mlflow.svc:5000"
      python3 - <<EOF
import mlflow, os
client = mlflow.tracking.MlflowClient(tracking_uri=os.environ["MLFLOW_TRACKING_URI"])
model = os.getenv("_MODEL_NAME")
versions = client.get_latest_versions(model, stages=["None"])
if versions:
    v = versions[0].version
    client.transition_model_version_stage(model, v, "Staging")
    print(f"✅ Promoted {model} v{v} to Staging")
else:
    print("❌ No model found.")
EOF
