feastProjectDir:
  git:
    url: https://github.com/dohuyduc2002/Credit-scoring-system-with-Kubeflow.git
    ref: 5c6f4f8
    featureRepoPath: src/feast/feature_repo

postgres:
  db: homecredit
  schema: feast
  user: postgres
  password: postgres
  host: postgres.database.svc.cluster.local

image: microwave1005/feast-spark:0.0.2

ui:
  serviceName: "feast-homecredit-ui"
  servicePort: 80 
  ingress:
    enabled: true
    className: nginx       
    host: feast.ducdh.com
