apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: kafka
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretAccessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: kafka
type: Opaque
stringData:
  postgres-credentials: |
    postgres_username={{ .Values.postgres.user }}
    postgres_password={{ .Values.postgres.password }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: {{ .Values.kafkaConnect.version }}
  image: {{ .Values.kafkaConnect.image }}
  replicas: {{ .Values.kafkaConnect.replicas }}
  bootstrapServers: {{ .Values.kafkaConnect.bootstrapServers }}
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status

    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1

    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider

    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schemas.enable: true
    key.converter.schema.registry.url: http://schema-registry-svc:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schemas.enable: true
    value.converter.schema.registry.url: http://schema-registry-svc:8081
    plugin.path: /opt/kafka/plugins
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: postgres-credentials
  template:
    connectContainer:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: AWS_SECRET_ACCESS_KEY