{{- range .Values.kafkaTopics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: chi-sink-connector-{{ .connector }}
  namespace: {{ $.Values.general.namespace }}
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: com.clickhouse.kafka.connect.ClickHouseSinkConnector
  tasksMax: 1
  config:
    topics: "{{ .name }}"
    topic2TableMap: "{{ .name }}={{ .mapping }}"
    hostname: chi-stream-chi-cluster-0-0.database.svc.cluster.local
    port: 8123
    database: {{ $.Values.chi.database }}
    username: {{ $.Values.chi.username }}
    password: {{ $.Values.chi.password }}

    flush.size: {{ $.Values.chi.flushSize }}

    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: rewrite
---
{{- end }}
