{{- range .Values.kafkaTopics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: bigquery-sink-connector-{{ .name }}
  namespace: {{ $.Values.general.namespace }}
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: com.wepay.kafka.connect.bigquery.BigQuerySinkConnector
  tasksMax: 1
  config:
    topics: "{{ .name }}"
    tasks.max: 1
    autoCreateTables: true
    allowNewBigQueryFields: true
    allowBigQueryRequiredFieldRelaxation: true
    project: homecredit_ds
    defaultDataset: "{{ .name }}"
    transforms: "RegexTransformation"
    transforms.RegexTransformation.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.RegexTransformation.regex: "(.*)-(.*)"
    transforms.RegexTransformation.replacement: "$1_$2"
    keyfile: "/mnt/creds/gcp-key.json"
---
{{- end }}
