apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
        - name: api
          image: microwave1005/prediction-api:latest
          imagePullPolicy: Always
          env:
            - name: MLFLOW_URI
              value: "http://mlflow.mlflow.svc.cluster.local:5000"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio-service.kubeflow.svc.cluster.local:9000"
            - name: AWS_USE_SSL
              value: "false"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: secret_key
            - name: AWS_REGION
              value: "us-east-1"
          ports:
            - containerPort: 8000  # FastAPI
            - containerPort: 8001  # Prometheus metrics
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  namespace: monitoring
spec:
  selector:
    app: prediction-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 8001
      targetPort: 8001
      name: metrics
