kafkaTopics:
  - name: bureau-balance
  - name: bureau
  - name: application
  - name: previous-application
  - name: credit-card-balance
  - name: pos-cash-balance
  - name: installments-payment

general:
  namespace: kafka

kafkaConnect:
  replicas: 1
  bootstrapServers: kafka-cluster-0-kafka-bootstrap.kafka.svc.cluster.local:9092
  image: microwave1005/kafka-connect-gcp:0.0.5
  version: "3.9.0"
