kafkaTopics:
  - name: homecredit.record.bureau_balance
    connector: bureau-balance

  - name: homecredit.record.bureau
    connector: bureau

  - name: homecredit.record.application
    connector: application

  - name: homecredit.record.previous_application
    connector: previous-application

  - name: homecredit.record.credit_card_balance
    connector: credit-card-balance

  - name: homecredit.record.pos_cash_balance
    connector: pos-cash-balance

  - name: homecredit.record.installments_payment
    connector: installments-payment

general:
  namespace: kafka

kafkaConnect:
  replicas: 1
  bootstrapServers: kafka-cluster-0-kafka-bootstrap.kafka.svc.cluster.local:9092
  image: microwave1005/kafka-connect-s3:0.0.1
  version: "4.0.0"

    
minio:
  accessKeyId: minio
  secretAccessKey: minio123
  s3PartSize: 5242880
  flushSize: 10000

postgres:
  user: postgres
  password: postgres
  