# kfp-access.yaml  ─────────────────────────────────────────────────────────────
#
# Namespace: kubeflow-user-example-com
# Purpose: Grant permissions + attach SA token for Notebook
# Effect: Spawner UI will show the checkbox “Allow access to Kubeflow Pipelines”

# (1) ServiceAccount used for the Notebook
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebooks-pipelines
  namespace: kubeflow-user-example-com
---
# (2) RoleBinding - assign “edit” permission on Kubeflow Pipelines to the SA created above
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notebooks-pipelines-edit
  namespace: kubeflow-user-example-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-pipelines-edit       # Predefined ClusterRole when Kubeflow is installed
subjects:
- kind: ServiceAccount
  name: notebooks-pipelines
  namespace: kubeflow-user-example-com
---
# (3) PodDefault – the “heart” of the checkbox
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: kubeflow-user-example-com
spec:
  desc: Allow access to Kubeflow Pipelines
  # This label is the condition for UI to show the checkbox
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  # The Pod will run under the created ServiceAccount when the checkbox is selected
  serviceAccountName: notebooks-pipelines
  env:
    # kfp.Client() reads this variable → path to the token
    - name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token
  # Mount the SA token using a projected volume (recommended by Kubeflow)
  volumes:
    - name: volume-kf-pipeline-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              audience: pipelines.kubeflow.org   # must match TOKEN_REVIEW_AUDIENCE
              expirationSeconds: 36000000 # Just a large number for testing; in real-world production, this might differ
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/pipelines
      name: volume-kf-pipeline-token
      readOnly: true
