apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.credentials.name }}
  namespace: {{ .Values.postgres.namespace }}
type: Opaque
stringData:
  postgres_username: {{ .Values.postgres.credentials.username }}
  postgres_password: {{ .Values.postgres.credentials.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.credentials.name }}
  namespace: {{ .Values.minio.namespace }}
type: Opaque
stringData:
  access-key: {{ .Values.minio.credentials.accessKey }}
  secret-key: {{ .Values.minio.credentials.secretKey }}
