{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}-monitor
  namespace: {{ .Values.service.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  namespaceSelector:
    matchNames:
      - {{ .Values.service.namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.interval }}
      path: /metrics
{{- end }}
